language: python
python:
- '3.7'
env:
- SERVER_IP_ADDRESS=138.68.189.32
branches:
  only:
  - A
  - main
install:
- python -m pip install --upgrade pip
- pip install --upgrade setuptools
- pip install wheel --no-cache
- pip install -r requirements.txt
- pip install psycopg2-binary
- pip install --upgrade setuptools
- pip install Flask-JWT-Extended
- pip install blinker
script:
- python -m unittest tests/test_login.py
- python -m unittest tests/test_register.py
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
# - ssh -o StrictHostKeyChecking=no -i ./travisDeploy root@138.68.189.32 'ls'
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@138.68.189.32 pwd
addons:
  ssh_known_hosts: 138.68.189.32
deploy:
  provider: script
  before_script: chmod + x login.sh
  overwrite: false
  script: bash ./login.sh
  on:
    branch: main
